spring.application.name=crud-tareas

spring.datasource.url=jdbc:mysql://localhost:3306/practica_web?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mysql2099.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true